name: simas
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  top_snackbar_flutter: ^1.0.0
  flutter:
    sdk: flutter




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # state management
  #bloc: ^7.0.0
  #flutter_bloc: ^7.0.1
  font_awesome_flutter: ^8.10.0
  geocoding: ^2.0.0
  geolocator: ^7.3.1
  local_auth: ^1.1.6


  # database
  #hive: ^2.0.4
  #hive_flutter: ^1.1.0

  # json parsing
  json_serializable: ^4.1.3
  intl: ^0.17.0
  bloc_test: ^8.0.2
  image_picker: ^0.8.2  
  file_picker: ^3.0.3
  shared_preferences: ^2.0.6
  dio: ^4.0.0
  date_field: ^2.0.1
  #flutter_form_builder: ^6.0.1
  #form_builder_file_picker: ^1.2.0-nullsafety.3
  permission_handler: ^8.1.4+2
  url_launcher: ^6.0.9
  splashscreen: ^1.3.5
  pdf_compressor: ^0.2.0
  path_provider: ^2.0.2
  percent_indicator: ^3.0.1
 
  cached_network_image: ^3.1.0
  flutter_svg: ^0.22.0
 
  
  progress_dialog: ^1.2.4
  downloads_path_provider: ^0.1.0
  flutter_launcher_icons: ^0.9.1

  #strava_flutter: ^1.2.2+62


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  hive_generator: ^1.1.0
  mockito: ^5.0.14

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_launcher.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/cover_bg.jpeg
   - assets/images/logo.png
   - assets/images/logoBankSinarmas.jpg
   - assets/images/background.png
   - assets/images/logo_sinarmas.png
   - assets/images/user_default.png
   - assets/icons/ic_izinTidakMasuk.png
   - assets/icons/ic_riwayat_izin.png
   - assets/icons/ic_riwayatAbsen.png
   - assets/icons/ic_riwayatKesehatan.png
   - assets/images/ambil_foto.png
   - assets/images/notif_success.png
   - assets/images/splash.png
   - assets/icons/sihadir.png
   - assets/icons/ic_launcher.png
   - assets/icons/kosong.png
   - assets/icons/group.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          style: italic 
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
          style: italic

  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
